source 'https://rubygems.org'

git_source(:github) { |_repo_name| "https://github.com/#{repo_name}" }

group :development, :test do
  gem 'pry' # debugging
  gem 'rspec' # testing
  gem 'rubocop' # code linter
  gem 'rubocop-rspec' # linter for rspec
end
